#Add values for any properties you wish to change when updating B2B Trading Partner Identifiers.
#Delete any lines that you don't want to update values.
#FlexDeploy properties or plain text are allowed.
#See the documentation at https://wiki.flexagon.com for more information.


######################## AVINSH_CORP ########################

AVINSH_CORP.317465592045120.EDI Interchange ID=124
AVINSH_CORP.36990536471679.AS2 Identifier=test0123
AVINSH_CORP.531584087610037.AS2 Identifier=AVN corp3

#Control Numbers
AVINSH_CORP.interchangeControlNumberStart=9
AVINSH_CORP.groupControlNumberStart=9
AVINSH_CORP.transactionControlNumberStart=9

##############################################################

######################## NEWTEST ########################

NEWTEST.490722137650053.AS2 Identifier=678

#Control Numbers
NEWTEST.interchangeControlNumberStart=
NEWTEST.groupControlNumberStart=
NEWTEST.transactionControlNumberStart=

##############################################################

######################## TESTTP ########################

TESTTP.4417613026390147.AS2 Identifier=test
TESTTP.4426131904862867.Application Partner ID=01

#Control Numbers
TESTTP.interchangeControlNumberStart=8
TESTTP.groupControlNumberStart=9
TESTTP.transactionControlNumberStart=7

##############################################################

######################## DUPLICATE_NAME ########################


#Control Numbers
DUPLICATE_NAME.interchangeControlNumberStart=
DUPLICATE_NAME.groupControlNumberStart=
DUPLICATE_NAME.transactionControlNumberStart=

##############################################################

######################## JAY_TRADING_PARTNER ########################

JAY_TRADING_PARTNER.3153260906101233.Application Partner ID=test_inbound_agreement

#Control Numbers
JAY_TRADING_PARTNER.interchangeControlNumberStart=
JAY_TRADING_PARTNER.groupControlNumberStart=
JAY_TRADING_PARTNER.transactionControlNumberStart=

##############################################################

######################## MUTHUCORP ########################

MUTHUCORP.2892859221053846.EDI Interchange ID Qualifier=ZZ
MUTHUCORP.2892859221078744.AS2 Identifier=MUTHUCORP_AS2

#Control Numbers
MUTHUCORP.interchangeControlNumberStart=
MUTHUCORP.groupControlNumberStart=
MUTHUCORP.transactionControlNumberStart=

##############################################################

######################## B2B_DEMO_PROJECT:SUPPLIER_A ########################

B2B_DEMO_PROJECT:SUPPLIER_A.3042866653386909.Application Partner ID=B2B Demo Supplier A

#Control Numbers
B2B_DEMO_PROJECT:SUPPLIER_A.interchangeControlNumberStart=
B2B_DEMO_PROJECT:SUPPLIER_A.groupControlNumberStart=
B2B_DEMO_PROJECT:SUPPLIER_A.transactionControlNumberStart=

##############################################################

######################## RAJ_B2B_TEST:RAJ_TRADING_PARTNER ########################

RAJ_B2B_TEST:RAJ_TRADING_PARTNER.604500079445274.Name=avtest

#Control Numbers
RAJ_B2B_TEST:RAJ_TRADING_PARTNER.interchangeControlNumberStart=9
RAJ_B2B_TEST:RAJ_TRADING_PARTNER.groupControlNumberStart=9
RAJ_B2B_TEST:RAJ_TRADING_PARTNER.transactionControlNumberStart=9

##############################################################

######################## EMILY_PROJECT:EM_B2B_TP1 ########################

EMILY_PROJECT:EM_B2B_TP1.8065479401205076.EDI Group ID=12345

#Control Numbers
EMILY_PROJECT:EM_B2B_TP1.interchangeControlNumberStart=
EMILY_PROJECT:EM_B2B_TP1.groupControlNumberStart=
EMILY_PROJECT:EM_B2B_TP1.transactionControlNumberStart=

##############################################################

######################## RAJ_LOOKUP_TEST:RG_TRADING_PARTNER ########################


#Control Numbers
RAJ_LOOKUP_TEST:RG_TRADING_PARTNER.interchangeControlNumberStart=
RAJ_LOOKUP_TEST:RG_TRADING_PARTNER.groupControlNumberStart=
RAJ_LOOKUP_TEST:RG_TRADING_PARTNER.transactionControlNumberStart=

##############################################################

######################## EMILY_PROJECT_COPY:EM_B2B_TP1 ########################

EMILY_PROJECT_COPY:EM_B2B_TP1.8065479401205076.EDI Group ID=12345

#Control Numbers
EMILY_PROJECT_COPY:EM_B2B_TP1.interchangeControlNumberStart=
EMILY_PROJECT_COPY:EM_B2B_TP1.groupControlNumberStart=
EMILY_PROJECT_COPY:EM_B2B_TP1.transactionControlNumberStart=

##############################################################
